# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: &excludes |
          (?x)^(
              .*\.blend|
              .*\.dae|
              .*\.mtl|
              .*\.obj|
              .*\.pgm|
              .*\.step|
              .*\.stl|
              .*\.js
          )$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: *excludes
      - id: trailing-whitespace
        exclude: *excludes

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    - id: shell-lint
      args: [--external-sources]

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
    - id: markdownlint

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    - id: dockerfilelint

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
    - id: cmake-lint

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: Format files with ClangFormat.
        entry: clang-format-15
        language: system
        files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|m|proto|vert)$
        args: [ "-fallback-style=none", "-i" ]
      - id: catkin_lint
        name: catkin_lint
        description: Check package.xml and cmake files
        entry: catkin_lint .
        language: system
        always_run: true
        pass_filenames: false
        args: [ "--strict" ]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.19.2
    hooks:
      - id: check-github-workflows
