apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: seerep-dev

namespace: seerep

resources:
  - persistent_volume.yaml
  - persistent_volume_claim.yaml
  - ca-secret-sealed.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configurations:
  - configuration/sealed-secret-config.yaml

configMapGenerator:
  - name:  seerep-cfg
    files:
      - seerep.cfg

secretGenerator:
  - name: ca-secret.yaml
    type: Opaque
