apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerep-pv-claim
spec:
  storageClassName: manual
  volumeName: seerep-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
