apiVersion: v1
kind: PersistentVolume
metadata:
  name: seerep-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/seerep-data
