name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-and-run-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agri-gaia/seerep_base:latest
      options: --user root

    steps:
    - uses: actions/checkout@v3
      with:
        path: src

    - name: Build the ros workspace
      run: |
        source /opt/ros/noetic/setup.bash
        catkin build --workspace $GITHUB_WORKSPACE/
      shell: bash

    - name: Test FlatBuffers write/load of image
      run: |
        source /opt/ros/noetic/setup.bash
        source $GITHUB_WORKSPACE/devel/setup.bash
        $GITHUB_WORKSPACE/devel/bin/flatbuffer-write-load-test
      shell: bash

    - name: Test Protobuf write/load of image
      run: |
        source /opt/ros/noetic/setup.bash
        source $GITHUB_WORKSPACE/devel/setup.bash
        $GITHUB_WORKSPACE/devel/bin/protobuf-write-load-test
      shell: bash

    - name: Test Conversion of ROS Messages to Flatbuffer
      run: |
        source /opt/ros/noetic/setup.bash
        source $GITHUB_WORKSPACE/devel/setup.bash
        catkin test seerep_ros_conversions_fb
      shell: bash
