apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: seerep-prod

namespace: seerep-prod

resources:
  - ./../../base
  - ca-secret-sealed.yaml
patchesStrategicMerge:
  - delete-secret.yaml
patches:
  - target:
      kind: PersistentVolume
    patch: |-
      - op: replace
        path: /metadata/name
        value: prod-seerep-data-pv
      - op: replace
        path: /spec/hostPath/path
        value: /media/data/seerep-prod
  - target:
      kind: PersistentVolumeClaim
    patch: |-
      - op: replace
        path: /spec/volumeName
        value: prod-seerep-data-pv
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30387
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: seerep-prod.robot.10.249.3.13.nip.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: seerep-prod.robot.10.249.3.13.nip.io
      - op: replace
        path: /spec/tls/0/secretName
        value: prod-seerep-ca

images:
  - name: seerep-server
    newTag: v1
